const START_POS = new BABYLON.Vector3(-10.0, 7.5, -10.0);
const START_FP = START_POS.clone().add(new BABYLON.Vector3(0, 2, 0))

const SCALE_HERO = new BABYLON.Vector3(1.0, 1.0, 1.0);
const TARGET_POS = new BABYLON.Vector3(0.0, 7.5, -20.0);
const FAR_CAM_POS = new BABYLON.Vector3(200.0, 45.0, 200.0);
const OBJ_POS_1 = new BABYLON.Vector3(10.0, 7, -10.0);
const OXYGEN_POS = new BABYLON.Vector3(-15.0, 7.6, -17.0);
const SPEED = 0.2; //m/s
const GRAVITY = -0.32; // m/s^2
const DELTA_FALLING = - (2 * SPEED * Math.cos(Math.PI / 4)) / GRAVITY;
const TXT_TASK = "MISSION 1: Your partner needs you. Take an oxygen tank and save his life!";
const TXT_FINISH = "Congrats, you saved your partner!!!";
const TASK_SOUND = "task1.wav"
const GOAL_SOUND = "success1.wav"
const BACK_SOUND = "back1.wav"
const TXT_GOAL = "MISSION 1: Completed!";
const SKY_PATH = "../images/galaxy.jpg";
const MAP_PATH = "moon_new.babylon";
const MAP_TEXT = "moon_text.jpg"
const BOY_PATH = "boy_new_clean.babylon";
const OBJ_PATH_1 = "nav_moon.babylon";
const OBJ_PATH_2 = "boy_new_target.babylon";
const MOON = true;
const MINI_MAP_PATH = "../images/height_moon.png";