const START_POS = new BABYLON.Vector3(-10.0, 22.0, -10.0);
const TARGET_POS = new BABYLON.Vector3(20.0, 22.0, 150.0);
const FAR_CAM_POS = new BABYLON.Vector3(-50.0, 50.0, 100.0);
const OBJ_POS_1 = new BABYLON.Vector3(-15.0, 18.0, 20.0)
const SPEED = 2.0;
const GRAVITY = -3.0;
const TXT_TASK = "MISSION 2: The rover fell down the Mars Valles, find it and fix it.";
const TASK_SOUND = "mission2.wav"
const BACK_SOUND = "mission2_back.wav"
const TXT_GOAL = "";
const SKY_PATH = "../images/orange.jpg";
const MAP_PATH = "mars5.babylon";
const BOY_PATH = "ACES2.babylon";
const OBJ_PATH_1 = "nav_mars.babylon";
const OBJ_PATH_2 = "";
const EARTH = false;
const MINI_MAP_PATH = "../images/heightmars.png";