const START_POS = new BABYLON.Vector3(-10.0, 0.0, -10.0);
const TARGET_POS = new BABYLON.Vector3(-60.0, 0.0, -105.0);
const FAR_CAM_POS = new BABYLON.Vector3(-50.0, 25.0, 100.0);
const OBJ_POS_1 = new BABYLON.Vector3(3.0, 0.0, 32.0);
const SPEED = 0.94; //m/s
const GRAVITY = -3.711; //m/s^2
const TXT_TASK = "MISSION 2: The rover fell down the Mars Valles, find it and fix it.";
const TASK_SOUND = "mission2.wav"
const BACK_SOUND = "mission2_back.wav"
const TXT_GOAL = "";
const SKY_PATH = "../images/orange.jpg";
const MAP_PATH = "mars.babylon";
const BOY_PATH = "ACES2.babylon";
const OBJ_PATH_1 = "nav_mars.babylon";
const OBJ_PATH_2 = "rover.babylon";
const MOON = false;
const MINI_MAP_PATH = "../images/height_mars.png";